### ISSUE TITLE
Found some misspellings in README.md

### ISSUE THREAD

**Issue by Cathesilta** [minetorch/minetorch#19]
I'm new to Pytorch library, and I found this one Minetorch is great for implementing training codes.
When I read the handbook I found some misspellings which could make the article less smooth to read. To make the contents more readable, especially for who has strict grammar habits, I've suggested a fixed version of README.md, with only fixing misspellings or words improperly belong to the sentences, and keeping proper nouns(eg. keywords in Pytorch, special words that I'm not familiar with) not changed. It'll be good if you took a look at the Pull Requests(I've done for it).

**Comment by louis-she** [comment]
https://github.com/minetorch/minetorch/pull/21  Thanks for contribution. 👍
